version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: bnvregistrudb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Nukazama7
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - my-network

  backend:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bnvregistrudb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Nukazama7
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - my-network

volumes:
  postgres-data:

networks:
  my-network: